dependencies:
- name: mariadb
  version: ~7.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled
- name: redis
  version: ~10.0.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
- name: projman
  version: 0.4.0
  repository: https://github.com/cloudve/helm-charts/raw/master/
- name: postgresql
  version: 8.6.4
  repository: https://kubernetes-charts.storage.googleapis.com/
